apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: github
  namespace: default
spec:
  interval: 5m0s
  type: oci
  url: oci://ghcr.io/cabs-test
  secretRef:
    name: github-credentials
